services:
  backend:
    container_name: backend
    command: fastapi dev app.py
    build: ./backend

    ports:
      - 4000:4000

  frontend:
    container_name: frontend
    command: npm run dev
    build: ./frontend

    volumes:
      - ./frontend:/home

    ports:
      -"4001:4001"

    environment:
      - HOST=0.0.0.0
      - PORT=4001

    depends_on:
      - backend
