version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        - HOST=0.0.0.0
        - PORT=4000
    # command: fastapi dev app.py --host 0.0.0.0 --port 4000
    ports:
      - 4000:4000

    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    # command: npm run dev
    volumes:
      - ./frontend/app:/app
      - /app/node_modules

    ports:
      - 4001:4000

    environment:
      - HOST=0.0.0.0
      - PORT=4000

    depends_on:
      - backend
